name: scenesynth
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - numpy
  - matplotlib
  - pytorch
  - torchvision 
  - torchmetrics
  - tqdm
  - pillow
  - wandb
  - ete3
  - pyyaml
  - pygraphviz
  - networkx
  - pip:
    - open3d
    - numba 