project: bedroom_filtered
name: query_object_rot_error

architecture:
  d_model: 128
  nhead: 4
  num_layers: 2
  loss: cross_entropy

training:
  epochs: 3
  batch_size: 64
  lr: 0.0003
  optimizer: adam
  train_split: 0.85
  val_split: 0.1