project: bedroom_filtered
name: longer_epoch_test

architecture:
  d_model: 128
  nhead: 4
  num_layers: 4
  loss: cross_entropy

training:
  epochs: 10
  batch_size: 64
  lr: 0.0003
  optimizer: adam
  train_split: 0.8
  val_split: 0.1