project: toy_test
name: overfit_to_one

architecture:
  d_model: 128
  nhead: 4
  num_layers: 2
  loss: cross_entropy

training:
  epochs: 10
  batch_size: 1
  lr: 0.0003
  optimizer: adam
  train_split: 0.8
  val_split: 0.1